on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test custom workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test publish
        uses: ./ # Uses an action in the root directory
        id: publish
        with:
          version: 0.1.0
          clientId: ${{ secret.CLIENT_ID }}
          clientSecret: ${{ secret.CLIENT_SECRET }}
          moduleDir: ./module

