on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Test publish
        uses: ./ # Uses an action in the root directory
        working-directory: module
        id: publish
        with:
          version: 0.1.0